### ISSUE TITLE
Sinon JS has moved and thus interstellar fails to install

### ISSUE THREAD

**Issue by raymens** [stellar/interstellar#5]
The package dependency `"sinon": "git://github.com/cjohansen/Sinon.JS#sinon-2.0",` seems to be causing a problem. The GH project seems to have moved to https://github.com/sinonjs/sinon and there doesn't seem to be a mention of a 2.0 version.

Error when `npm install -g interstellar` or when I clone this repo and do a `npm install`:

```
Failed resolving git HEAD (...) fatal: ambiguous argument 'sinon-2.0': unknown revision or path not in the working tree
....
```

**Update:**
Sinon is on NPM: `https://www.npmjs.com/package/sinon`
and changing the dependency to  `"sinon": "git://github.com/sinonjs/sinon",` seems to be working

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/interstellar/commit/42733ce0f0dc5ba92336b1c54edeb712f8a2c895. `npm install -g interstellar@0.0.7` to upgrade.
